CREATE OR REPLACE PROCEDURE SEL_EMPNO
    (
        --IN : 내부적으로 사용, OUT : 프로시저 밖에서 사용
        VEMPNO IN EMP.EMPNO%TYPE,
        VENAME OUT EMP.ENAME%TYPE,
        VSAL OUT EMP.SAL%TYPE,
        VJOB OUT EMP.JOB%TYPE
    )
IS
BEGIN
    SELECT ENAME, SAL, JOB INTO VENAME, VSAL, VJOB
    FROM EMP
    WHERE EMPNO = VEMPNO;
END;
/